---
apiVersion: v1
kind: Service
metadata:
  name: app01-svc
  namespace: demo-web-service
spec:
  ports:
  - name: app01
    port: 8080
    protocol: TCP
  selector:
    app: app01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app01
  name: app01
  namespace: demo-web-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      annotations: null
      labels:
        app: app01
    spec:
      containers:
      - image: devopsabi/demo-app-k8s:01
        name: app01
        ports:
        - containerPort: 8080
