apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-web
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://devopsabi.github.io/helm-repo/
    targetRevision: HEAD
    chart: app01
    targetRevision: 0.1.0
    helm:
      valuesObject:
        replica:
          replicaCount: 3

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-web

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
